config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/policy', to: 'static_pages#policy'
  get '/timer', to: 'static_pages#timer'
  get '/week', to: 'static_pages#week'
  post '/week', to: 'static_pages#week_specified'
  get '/month', to: 'static_pages#month'
  post '/month', to: 'static_pages#month_specified'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: "users/confirmations",
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: :show do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy, :show] do
    resources :comments, only: [:create, :destroy]
  end
  resources :tasks, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.includes([:user]).recent.page(params[:page]).per(Constants::FEED_NUM)
      @search_user = User.ransack(params[:q])
      @users = @search_user.result(distinct: true).page(params[:page]).per(Constants::SEARCH_USER_NUM) if params[:q].present?
      @search_micropost = Micropost.ransack(params[:p], search_key: :p)
      @microposts = @search_micropost.result(distinct: true).includes([:user]).recent.page(params[:page]).per(Constants::SEARCH_MICROPOST_NUM) if params[:p].present?
    end
  end

  def policy
  end

  def timer
    # task あり micropost を create 後のみ休憩のダイアログを表示する
    @break_time_on = params[:break_time]
    # micropost 作成
    @micropost = current_user.microposts.build
    @last_task = last_task
    # task 作成, 一覧
    @task = current_user.tasks.build
    @tasks = current_user.tasks.recent
    # task グラフ
    @tasks_today = tasks_day_set(Time.zone.now)
    # Today's task
    @microposts_with_task_today = microposts_with_task(Time.zone.now)
  end

  def week
    moment = Time.zone.now
    @start_day = moment.beginning_of_week
    @end_day = moment.end_of_week
    @task_names_week = task_names_term_distinct(moment.all_week)
    @tasks_week = tasks_week_set(moment)
    @tasks_total_time_week = to_h_and_m(tasks_total_time_term(@tasks_week))
  end

  def week_specified
    moment = params[:date].in_time_zone
    moment = Time.zone.now if moment.nil?
    @start_day = moment.beginning_of_week
    @end_day = moment.end_of_week
    @task_names_week = task_names_term_distinct(moment.all_week)
    @tasks_week = tasks_week_set(moment)
    @tasks_total_time_week = to_h_and_m(tasks_total_time_term(@tasks_week))
    render :week
  end

  def month
    @moment = Time.zone.now
    @task_names_month = task_names_term_distinct(@moment.all_month)
    @tasks_month = tasks_month_set(@moment)
    @tasks_total_time_month = to_h_and_m(tasks_total_time_term(@tasks_month))
  end

  def month_specified
    @moment = select_time_zone(params[:date])
    @moment = Time.zone.now if @moment.nil?
    @task_names_month = task_names_term_distinct(@moment.all_month)
    @tasks_month = tasks_month_set(@moment)
    @tasks_total_time_month = to_h_and_m(tasks_total_time_term(@tasks_month))
    render :month
  end

  protected

  # minutes を hours, minutes 表記に変換する
  def to_h_and_m(minutes)
    (minutes / 60).to_s + ' h ' + format('%02d', minutes % 60) + " m"
  end

  # date_select タグから time zone を取得する
  def select_time_zone(date)
    year = format('%04d', date["#{Time.zone.today}(1i)"])
    month = format('%02d', date["#{Time.zone.today}(2i)"])
    day = format('%02d', date["#{Time.zone.today}(3i)"])
    (year + '-' + month + '-' + day).in_time_zone
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def task_time_value
    if current_user.task_time
      current_user.task_time
    else
      Constants::DEFAULT_TASK_TIME
    end
  end

  def break_time_value
    if current_user.break_time
      current_user.break_time
    else
      Constants::DEFAULT_BREAK_TIME
    end
  end
end

app/views/static_pages/_audios.html.erb
<%= audio_tag("decision6.mp3",id:"decision6") %>
<%= audio_tag("decision22.mp3",id:"decision22") %>
<%= audio_tag("bath-thapon1.mp3",id:"bath-thapon1") %>
<%= audio_tag("bath-out1.mp3",id:"bath-out1") %>

app/views/static_pages/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <% @feed_items.each do |feed_item| %>
      <%= render 'shared/micropost', micropost: feed_item %>
    <% end %>
  </ol>
  <%= paginate @feed_items, params: { controller: :static_pages, action: :home} %>
<% end %>

app/views/static_pages/_modal_js.html.erb
<%# timer.js 下部とほぼ同様の script %>
<%# モーダルウィンドウから micropost create 失敗時のために記述 %>
<script>
  document.addEventListener("DOMContentLoaded", function(event) {
    $(function() {
      record_task();

      //モーダルウィンドウで micropost_form を出現させる
      function record_task() {
        if( $("#modal-overlay")[0] ) return false;
        $("body").append('<div id="modal-overlay"></div>');
        $("#modal-overlay").fadeIn( 100 );
        $("#modal-content").html(
          $(".modal-open").prop('innerHTML')
        );
        $('#modal-content .modal-micropost-form').css('display','block');
        centeringModalSyncer();
        $("#modal-content").fadeIn( 100 );
      }

      //リサイズされたら、センタリングをする
      $(window).resize(centeringModalSyncer);

      function centeringModalSyncer() {
        var w = $(window).width();
        var h = $(window).height();
        var cw = $("#modal-content").outerWidth();
        var ch = $("#modal-content").outerHeight();

        $("#modal-content").css( {"left": ((w - cw)/2) + "px","top": ((h - ch)/2) + "px"} );
      }
    });
  });
</script>

app/views/static_pages/_search_micropost.html.erb
<div class="search-box clearfix">
  <%= search_form_for @search_micropost, as: :p, url: root_path do |f| %>
    <%= f.search_field :content_or_task_cont, placeholder: "Content or Task", class: "search-field", id: "search-field-micropost" %>
    <%= f.button :type => "submit", class: "search-btn", id: "search-btn-micropost" do %>
      <i class="fas fa-search"></i>
    <% end %>
  <% end %>
</div>
<% if defined? @microposts %>
  <ul class="microposts">
    <% @microposts.each do |micropost| %>
      <%= render 'shared/micropost', micropost: micropost %>
    <% end %>
  </ul>
  <%= paginate @microposts %>
<% end %>

app/views/static_pages/_search_user.html.erb
<div class="search-box clearfix">
  <%= search_form_for @search_user, url: root_path do |f| %>
    <%= f.search_field :name_or_profile_cont, placeholder: "Name or Profile", class: "search-field", id: "search-field-user" %>
    <%= f.button :type => "submit", class: "search-btn", id: "search-btn-user" do %>
      <i class="fas fa-search"></i>
    <% end %>
  <% end %>
</div>
<% if defined? @users %>
  <%= render 'shared/user_index', users: @users %>
<% end %>

app/views/static_pages/_task_graph_day.html.erb
<figure>
  <div class="x-axis">
    <ul class="legend">
      <% tasks_day[2].each do |name, time| %>
        <li><%= name %></li>
      <% end %>
    </ul>
  </div>
  <div class="graphic">
    <div class="row">
      <h6><%= tasks_day[0].month %>/<%= tasks_day[0].day %> (<%= tasks_day[1] %>)</h6>
      <div class="chart" id="chart-0">
        <% tasks_day[2].each do |name, time| %>
          <span class="block" id="<%= name %>" title="<%= name %>: <%= time %> minutes">
            <span class="value"><%= time %></span>
          </span>
        <% end %>
      </div>
    </div>
  </div>
</figure>

app/views/static_pages/_task_graph_term.html.erb
<figure>
  <div class="x-axis">
    <ul class="legend">
      <% task_names_term.each do |name| %>
        <li><%= name %></li>
      <% end %>
    </ul>
  </div>
  <div class="graphic">
    <% tasks_term.each_with_index do |tasks_day, i| %>
      <div class="row">
        <h6 class=".day-<%= i %>"><%= tasks_day[0].month %>/<%= tasks_day[0].day %> (<%= tasks_day[1] %>)</h6>
        <div class="chart" id="chart-<%= i %>">
          <% tasks_day[2].each do |name, time| %>
            <span class="block" id="<%= name %>" title="<%= name %>: <%= time %> minutes">
              <span class="value"><%= time %></span>
            </span>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</figure>

app/views/static_pages/_timer_box.html.erb
<section class="container--extend">
  <div class="clearfix timer-header">
    <div id="timer-name">Timer</div>
    <div id="vol-slide">
      <span id="vol-icon">
        <i class="fas fa-volume-up vol-style"></i>
      </span>
    </div>
    <div class="controls">
      <button class="btn btn-secondary btn-lg" id="start" disabled="disabled">
        <i class="fas fa-play play-style"></i>
      </button>
    </div>
  </div>
  <div class="shadow border border-dark" id="timer">00:00</div>
  <input name="task-time" type="hidden" value=<%= task_time_value %> class="set-task-time">
  <div class="timer-info">タイマーはプロフィールから変更できます</div>
</section>

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
  <div class="row">
    <aside class="col-md-4">
      <%= render 'shared/aside_profile', users: nil, user: current_user %>
      <section class="micropost_form">
        <%= render 'shared/micropost_form', micropost: @micropost, need_task: false %>
      </section>
    </aside>
    <div class="col-md-8">
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <a href="#tab-feed" class="nav-link active" data-toggle="tab">フィード</a>
        </li>
        <li class="nav-item">
          <a href="#tab-user" class="nav-link" data-toggle="tab">アカウント検索</a>
        </li>
        <li class="nav-item">
          <a href="#tab-micropost" class="nav-link" data-toggle="tab">投稿検索</a>
        </li>
      </ul>
      <div class="tab-content">
        <div id="tab-feed" class="tab-pane active">
          <%= render 'static_pages/feed' %>
        </div>
        <div id="tab-user" class="tab-pane">
          <%= render 'static_pages/search_user' %>
        </div>
        <div id="tab-micropost" class="tab-pane">
          <%= render 'static_pages/search_micropost' %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="home-wrapper">
    <h1><%= Constants::APP_NAME %></h1><br>
    <p>タイマーで区切ってタスクに集中</p>
    <p>終わったら記録を残そう</p>
    <p>日々の積み重ねを見える化してヤル気を継続！</p>
    <div class="new-user-link">
      <hr style="max-width: 400px;">
      <%= link_to "ユーザー登録", new_user_registration_path %>
      <%= link_to "ログイン", new_user_session_path %>
    </div>
  </div>
<% end %>

app/views/static_pages/month.html.erb
<% provide(:title, "月") %>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= link_to "今日", timer_path, data: {"turbolinks" => false}, class: "graph-change" %>
    <%= link_to "週毎", week_path, data: {"turbolinks" => false}, class: "graph-change" %>
    <div class="change-term">
      <%= form_with(url: month_path, local: true) do %>
        <%= date_select :date, Time.zone.today.to_s, discard_day: true, use_month_numbers: true, with_css_classes: "noname" %>
        <%= button_tag type: "submit", class: "btn btn-warning btn-sm btn-term" do %>
          <i class="fas fa-calendar-alt"></i> 変更（月）
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="col-md-12">
    <h1 class="display-term">Task ( <%= @moment.year %>/<%= @moment.month %> )</h1>
    <h3 style="text-align: center;">total: <%= @tasks_total_time_month %></h3>
    <%= render 'static_pages/task_graph_term', tasks_term: @tasks_month, task_names_term: @task_names_month %>
  </div>
</div>

app/views/static_pages/policy.html.erb
<% provide(:title, "利用規約") %>
<div class="row">
  <div class="col-md-12">
    <div class="wrapHINAGATA">
      <h1>利用規約</h1>
      <p>この利用規約（以下，「本規約」といいます。）は，<strong><%= Constants::APP_NAME %></strong>（以下，「当社」といいます。）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。</p>
      <h2>第1条（適用）</h2>
      <ol>
        <li>本規約は，ユーザーと当社との間の本サービスの利用に関わる一切の関係に適用されるものとします。</li>
        <li>当社は本サービスに関し，本規約のほか，ご利用にあたってのルール等，各種の定め（以下，「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず，本規約の一部を構成するものとします。</li>
        <li>本規約の規定が前条の個別規定の規定と矛盾する場合には，個別規定において特段の定めなき限り，個別規定の規定が優先されるものとします。</li>
      </ol>
      <h2>第2条（利用登録）</h2>
      <ol>
        <li>本サービスにおいては，登録希望者が本規約に同意の上，当社の定める方法によって利用登録を申請し，当社がこの承認を登録希望者に通知することによって，利用登録が完了するものとします。</li>
        <li>当社は，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。
          <ol>
            <li>利用登録の申請に際して虚偽の事項を届け出た場合</li>
            <li>本規約に違反したことがある者からの申請である場合</li>
            <li>その他，当社が利用登録を相当でないと判断した場合</li>
          </ol>
        </li>
      </ol>
      <h2>第3条（ユーザーIDおよびパスワードの管理）</h2>
      <ol>
        <li>ユーザーは，自己の責任において，本サービスのユーザーIDおよびパスワードを適切に管理するものとします。</li>
        <li>ユーザーは，いかなる場合にも，ユーザーIDおよびパスワードを第三者に譲渡または貸与し，もしくは第三者と共用することはできません。当社は，ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。</li>
        <li>ユーザーID及びパスワードが第三者によって使用されたことによって生じた損害は，当社に故意又は重大な過失がある場合を除き，当社は一切の責任を負わないものとします。</li>
      </ol>
      <h2>第4条（利用料金および支払方法）</h2>
      <ol>
        <li>ユーザーは，本サービスを全て無料で利用することができます。</li>
      </ol>
      <h2>第5条（禁止事項）</h2>
      <p>ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。</p>
      <ol>
        <li>法令または公序良俗に違反する行為</li>
        <li>犯罪行為に関連する行為</li>
        <li>当社，本サービスの他のユーザー，または第三者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為</li>
        <li>当社のサービスの運営を妨害するおそれのある行為</li>
        <li>他のユーザーに関する個人情報等を収集または蓄積する行為</li>
        <li>不正アクセスをし，またはこれを試みる行為</li>
        <li>他のユーザーに成りすます行為</li>
        <li>当社のサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為</li>
        <li>当社，本サービスの他のユーザーまたは第三者の知的財産権，肖像権，プライバシー，名誉その他の権利または利益を侵害する行為</li>
        <li>以下の表現を含み，または含むと当社が判断する内容を本サービス上に投稿し，または送信する行為
          <ol>
            <li>過度に暴力的な表現</li>
            <li>露骨な性的表現</li>
            <li>人種，国籍，信条，性別，社会的身分，門地等による差別につながる表現</li>
            <li>自殺，自傷行為，薬物乱用を誘引または助長する表現</li>
            <li>その他反社会的な内容を含み他人に不快感を与える表現</li>
          </ol>
        </li>
        <li>以下を目的とし，または目的とすると当社が判断する行為
          <ol>
            <li>営業，宣伝，広告，勧誘，その他営利を目的とする行為（当社の認めたものを除きます。）</li>
            <li>性行為やわいせつな行為を目的とする行為</li>
            <li>面識のない異性との出会いや交際を目的とする行為</li>
            <li>他のユーザーに対する嫌がらせや誹謗中傷を目的とする行為</li>
            <li>当社，本サービスの他のユーザー，または第三者に不利益，損害または不快感を与えることを目的とする行為</li>
            <li>その他本サービスが予定している利用目的と異なる目的で本サービスを利用する行為</li>
          </ol>
        </li>
        <li>宗教活動または宗教団体への勧誘行為</li>
        <li>その他，当社が不適切と判断する行為</li>
      </ol>
      <h2>第6条（本サービスの提供の停止等）</h2>
      <ol>
        <li>当社は，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。
      <ol>
        <li>本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</li>
        <li>地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合</li>
        <li>コンピュータまたは通信回線等が事故により停止した場合</li>
        <li>その他，当社が本サービスの提供が困難と判断した場合</li>
      </ol>
      </li>
      <li>当社は，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害についても，一切の責任を負わないものとします。</li>
      </ol>
      <h2>第7条（著作権）</h2>
      <ol>
        <li>ユーザーは，自ら著作権等の必要な知的財産権を有するか，または必要な権利者の許諾を得た文章，画像や映像等の情報に関してのみ，本サービスを利用し，投稿ないしアップロードすることができるものとします。</li>
        <li>ユーザーが本サービスを利用して投稿ないしアップロードした文章，画像，映像等の著作権については，当該ユーザーその他既存の権利者に留保されるものとします。ただし，当社は，本サービスを利用して投稿ないしアップロードされた文章，画像，映像等について，本サービスの改良，品質の向上，または不備の是正等ならびに本サービスの周知宣伝等に必要な範囲で利用できるものとし，ユーザーは，この利用に関して，著作者人格権を行使しないものとします。</li>
        <li>前項本文の定めるものを除き，本サービスおよび本サービスに関連する一切の情報についての著作権およびその他の知的財産権はすべて当社または当社にその利用を許諾した権利者に帰属し，ユーザーは無断で複製，譲渡，貸与，翻訳，改変，転載，公衆送信（送信可能化を含みます。），伝送，配布，出版，営業使用等をしてはならないものとします。</li>
      </ol>
      <h2>第8条（利用制限および登録抹消）</h2>
      <ol>
        <li>当社は，ユーザーが以下のいずれかに該当する場合には，事前の通知なく，投稿データを削除し，ユーザーに対して本サービスの全部もしくは一部の利用を制限しまたはユーザーとしての登録を抹消することができるものとします。
          <ol>
            <li>本規約のいずれかの条項に違反した場合</li>
            <li>登録事項に虚偽の事実があることが判明した場合</li>
            <li>当社からの連絡に対し，一定期間返答がない場合</li>
            <li>本サービスについて，最終の利用から一定期間利用がない場合</li>
            <li>その他，当社が本サービスの利用を適当でないと判断した場合</li>
          </ol>
        </li>
        <li>前項各号のいずれかに該当した場合，ユーザーは，当然に当社に対する一切の債務について期限の利益を失い，その時点において負担する一切の債務を直ちに一括して弁済しなければなりません。</li>
        <li>当社は，本条に基づき当社が行った行為によりユーザーに生じた損害について，一切の責任を負いません。</li>
      </ol>
      <h2>第9条（退会）</h2>
      <p>ユーザーは，当社の定める退会手続により，本サービスから退会できるものとします。</p>
      <h2>第10条（保証の否認および免責事項）</h2>
      <ol>
        <li>当社は，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。</li>
        <li>当社は，本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。ただし，本サービスに関する当社とユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合，この免責規定は適用されません。</li>
        <li>前項ただし書に定める場合であっても，当社は，当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（当社またはユーザーが損害発生につき予見し，または予見し得た場合を含みます。）について一切の責任を負いません。また，当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は，ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。</li>
        <li>当社は，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。</li>
      </ol>
      <h2>第11条（サービス内容の変更等）</h2>
      <p>当社は，ユーザーに通知することなく，本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし，これによってユーザーに生じた損害について一切の責任を負いません。</p>
      <h2>第12条（利用規約の変更）</h2>
      <p>当社は，必要と判断した場合には，ユーザーに通知することなくいつでも本規約を変更することができるものとします。なお，本規約の変更後，本サービスの利用を開始した場合には，当該ユーザーは変更後の規約に同意したものとみなします。</p>
      <h2>第13条（個人情報の取扱い）</h2>
      <p>当社は，本サービスの利用によって取得する個人情報については，当社「プライバシーポリシー」に従い適切に取り扱うものとします。</p>
      <h2>第14条（通知または連絡）</h2>
      <p>ユーザーと当社との間の通知または連絡は，当社の定める方法によって行うものとします。当社は,ユーザーから,当社が別途定める方式に従った変更届け出がない限り,現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い,これらは,発信時にユーザーへ到達したものとみなします。</p>
      <h2>第15条（権利義務の譲渡の禁止）</h2>
      <p>ユーザーは，当社の書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。</p>
      <h2>第16条（準拠法・裁判管轄）</h2>
      <ol>
        <li>本規約の解釈にあたっては，日本法を準拠法とします。</li>
        <li>本サービスに関して紛争が生じた場合には，当社の本店所在地を管轄する裁判所を専属的合意管轄とします。</li>
      </ol>
      <p class="tR">以上</p>
    </div>
  </div>
</div>

app/views/static_pages/timer.html.erb
<% provide(:title, "Timer") %>
<div class="row">
  <aside class="col-md-4">
    <!-- 休憩用タイマー -->
    <span hidden id="break-time-on"><%= @break_time_on %></span>
    <input name="break-time" type="hidden" value=<%= break_time_value %> class="set-break-time">
    <!-- Timer -->
    <%= render 'static_pages/timer_box' %>
    <!-- タスク追加 & 一覧表示 -->
    <section class="task_form">
      <%= render 'shared/task_form', task: @task %>
    </section>
    <% if @tasks.any? %>
      <ol class="tasks">
        <% @tasks.each do |task| %>
          <%= render 'shared/task', task: task %>
        <% end %>
      </ol>
    <% end %>
  </aside>
  <div class="col-md-8">
    <!-- タスクグラフ -->
    <div data-turbolinks="false">
      <%= link_to "週毎", week_path, data: {"turbolinks" => false}, class: "graph-change" %>
      <%= link_to "月毎", month_path, data: {"turbolinks" => false}, class: "graph-change" %>
    </div>
    <%= render 'static_pages/task_graph_day', tasks_day: @tasks_today %>
    <!-- 本日のタスク内容 -->
    <% if @microposts_with_task_today.any? %>
      <h3>Today's task (<%= @microposts_with_task_today.count %>)</h3>
      <ol class="microposts">
        <% @microposts_with_task_today.each do |micropost| %>
          <%= render 'shared/micropost', micropost: micropost %>
        <% end %>
      </ol>
      <%= paginate @microposts_with_task_today %>
    <% end %>
  </div>
</div>
<!--（モーダルウィンドウ）マイクロポストフォーム -->
<div class="modal-open">
  <div class="modal-micropost-form">
    <section class="micropost_form">
      <%= render 'shared/micropost_form', micropost: @micropost, need_task: true, last_task: @last_task %>
    </section>
  </div>
</div>
<div id="modal-content"></div>
<!-- タイマー音源 -->
<%= render 'static_pages/audios' %>
<% if defined? @show_modal %>
  <%= render 'static_pages/modal_js' %>
<% end %>

app/views/static_pages/week.html.erb
<% provide(:title, "週") %>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= link_to "今日", timer_path, data: {"turbolinks" => false}, class: "graph-change" %>
    <%= link_to "月毎", month_path, data: {"turbolinks" => false}, class: "graph-change" %>
    <div class="change-term">
      <%= form_with(url: week_path, local: true) do %>
        <%= date_field_tag :date, Time.zone.today.to_s, class: "date-field" %>
        <%= button_tag type: "submit", class: "btn btn-info btn-sm btn-term" do %>
          <i class="fas fa-calendar-alt"></i> 変更（週）
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="col-md-12">
    <h1 class="display-term">
      Task ( <%= @start_day.year %>/<%= @start_day.month %>/<%= @start_day.day %>
       ~ <%= @end_day.year %>/<%= @end_day.month %>/<%= @end_day.day %> )
    </h1>
    <h3 style="text-align: center;">total: <%= @tasks_total_time_week %></h3>
    <%= render 'static_pages/task_graph_term', tasks_term: @tasks_week, task_names_term: @task_names_week %>
  </div>
</div>