config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/policy', to: 'static_pages#policy'
  get '/timer', to: 'static_pages#timer'
  get '/week', to: 'static_pages#week'
  post '/week', to: 'static_pages#week_specified'
  get '/month', to: 'static_pages#month'
  post '/month', to: 'static_pages#month_specified'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: "users/confirmations",
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: :show do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy, :show] do
    resources :comments, only: [:create, :destroy]
  end
  resources :tasks, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/views/shared/_aside_profile.html.erb
<section class="user_info">
  <span class="aside-profile-top">
    <%= link_to user_path(user) do %>
      <%= gravatar_for(user, size: 80) %>
      <h5 class="user-name"><%= user.name %></h5>
    <% end %>
  </span><br>
  <span>投稿<strong><%= user.microposts.count %></strong>件</span>
</section>
<section>
  <%= render 'shared/stats', user: user %>
  <% if users.present? %>
    <div class="user_avatars">
      <% users.each do |u| %>
        <%= link_to gravatar_for(u, size: 30), user_path(u) %>
      <% end %>
    </div>
  <% end %>
</section>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <% unless defined? errors_num_unnecessary %>
      <div class="alert alert-danger">
        <%= object.errors.count %>つエラーがあります
      </div>
    <% end %>
    <ul class="errors-full-messages">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= paginate @feed_items, params: { controller: :static_pages, action: :home} %>
<% end %>

app/views/shared/_like.html.erb
<span class="like">
  <% if micropost.like?(current_user) %>
    <%= form_with(model: micropost.likes.find_by(user_id: current_user.id), method: :delete, remote: true) do |f| %>
      <%= button_tag class: "btn btn-sm btn-like" do %>
        <i class="fas fa-heart heart-like"></i>
        <%= content_tag :span, "#{micropost.likes_count}" %>
      <% end %>
    <% end %>
  <% else %>
    <%= form_with(model: micropost.likes.build, remote: true) do |f| %>
      <%= hidden_field_tag :micropost_id, micropost.id %>
      <%= button_tag class: "btn btn-sm btn-like" do %>
        <i class="far fa-heart heart-like"></i>
        <%= content_tag :span, "#{micropost.likes_count}" %>
      <% end %>
    <% end %>
  <% end %>
</span>

app/views/shared/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <% if micropost.task %>
    <div class="task-info">
      <span class="task">#<%= micropost.task %></span>
      <span class="task-time"> (<%= micropost.task_time %><small>分</small>)</span>
    </div><br>
  <% end %>
  <span class="content"><%= safe_join(micropost.content.split("\n"), tag(:br)) %></span>
  <span class="timestamp">
    <div class="time-ago"><%= time_ago_in_words(micropost.created_at) %>前</div>
    <%= link_to micropost_path(micropost), class: "comment-link" do %>
      <i class="far fa-comments"></i> <%= micropost.comments.count %>
    <% end %>
    <%= render 'shared/like', micropost: micropost %>
    <% if current_user == micropost.user %>
      <%= link_to "削除", micropost, method: :delete, data: { confirm: "本当に削除しますか？" } %>
    <% end %>
  </span>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_with(model: micropost, local: true, id: "micropost-form-with") do |f| %>
  <%= render 'shared/error_messages', errors_num_unnecessary: true, object: f.object %>
  <div class="field">
    <% if need_task %>
      <%= f.hidden_field :task_time, value: task_time_value %>
      <%= f.label :task, "タスク選択" %>
      <%= f.collection_select :task, @tasks, :name, :name, {selected: last_task}, {id: "micropost-task-select"} %>
    <% end %>
    <%= f.text_area :content, placeholder: "Content", id: "micropost-content-area", maxlength: 200 %>
  </div>
  <%= button_tag type: "submit", class: "btn btn-primary btn-block", id: "btn-post" do %>
    <i class="far fa-edit"></i> 投稿
  <% end %>
<% end %>

app/views/shared/_notifications.html.erb
<%= link_to notifications_path, class: "nav-link" do %>
  <% if unchecked_notifications %>
    <span class="fa-stack">
      <i class="far fa-bell fa-lg fa-stack-2x" style="font-size: 1.5em;"></i>
      <i class="fas fa-circle n-circle fa-stack-1x"></i>
    </span>
     <span class="notificaiton-icon-text-wrapper">
      <span class="notification-icon-text">通知</span>
    </span>
  <% else %>
    <i class="far fa-bell fa-lg" style="font-size: 1.5em;"></i> 通知
  <% end %>
<% end %>

app/views/shared/_stats.html.erb
<% user ||= current_user %>
<div class="stats">
  <a href="<%= followers_user_path(user) %>">
    フォロワー
    <strong id="followers" class="stat">
      <%= user.followers.count %>人
    </strong>
  </a>
  <a href="<%= following_user_path(user) %>">
    フォロー中
    <strong id="following" class="stat">
      <%= user.following.count %>人
    </strong>
  </a>
</div>

app/views/shared/_task.html.erb
<li id="task-<%= task.id %>">
  <div class="name"><%= task.name %></div>
  <div class="delete-task">
    <% if current_user == task.user %>
      <%= link_to "削除", task, method: :delete, data: { confirm: "本当に削除しますか？" } %>
    <% end %>
  <div>
</li>

app/views/shared/_task_form.html.erb
<%= form_with(model: task, local: true) do |f| %>
  <div class="clearfix">
    <%= f.text_field :name, placeholder: "New Task", class: "task-field", id: "task-name-field", maxlength: 50 %>
    <%= f.button :type => "submit", class: "add-btn", id: "add-btn-task" do %>
      <i class="fas fa-plus"></i>
    <% end %>
  </div>
<% end %>

app/views/shared/_user_index.html.erb
<ul class="users follow">
  <% users.each do |user| %>
    <li>
      <%= link_to gravatar_for(user, size: 50), user_path(user) %>
        <div class="users-index-name">
        <%= link_to user.name, user_path(user) %>
        <%= user.profile %>
      </div>
    </li>
  <% end %>
</ul>
<%= paginate users %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "プロフィール", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>