config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/policy', to: 'static_pages#policy'
  get '/timer', to: 'static_pages#timer'
  get '/week', to: 'static_pages#week'
  post '/week', to: 'static_pages#week_specified'
  get '/month', to: 'static_pages#month'
  post '/month', to: 'static_pages#month_specified'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: "users/confirmations",
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: :show do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy, :show] do
    resources :comments, only: [:create, :destroy]
  end
  resources :tasks, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :notifications, dependent: :destroy
  scope :recent, -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 200 }

  def like(user)
    likes.create(user_id: user.id)
  end

  def unlike(user)
    likes.find_by(user_id: user.id).destroy
  end

  def like?(user)
    likes.pluck(:user_id).include?(user.id)
  end

  def notify_like(visitor)
    # 既にいいね済であれば何もしない
    temp = Notification.where(["visitor_id = ? and visited_id = ? and micropost_id = ? and action = ? ", visitor.id, user_id, id, 'like'])
    return if temp.present?

    notification = visitor.active_notifications.build(micropost_id: id, visited_id: user_id, action: 'like')
    # 自分の投稿へのいいねは通知済とする
    notification.checked = true if notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
  end

  def notify_comment(visitor, comment_id)
    temp_ids = Comment.select(:user_id).where(micropost_id: id).where.not(user_id: visitor.id).distinct
    # 自分以外でまだ誰もコメントしていない場合は、投稿者に通知を送る
    if temp_ids.blank?
      save_notification_comment(visitor, comment_id, user_id)
    # 自分以外から既にコメントがされている場合は、コメントしている全員へ通知を送る
    else
      temp_ids.each do |temp_id|
        save_notification_comment(visitor, comment_id, temp_id[:user_id])
      end
    end
  end

  def save_notification_comment(visitor, comment_id, visited_id)
    notification = visitor.active_notifications.build(micropost_id: id, comment_id: comment_id, visited_id: visited_id, action: 'comment')
    # 自分の投稿へのコメントは通知済とする
    notification.checked = true if notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :correct_user, only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "投稿されました！"
      if @micropost.task.blank?
        redirect_to root_url
      else
        redirect_to timer_url(break_time: "on")
      end
    else
      if @micropost.task.blank?
        @feed_items = current_user.feed.includes([:user]).recent.page(params[:page]).per(Constants::FEED_NUM)
        @search_user = User.ransack(params[:q])
        @users = @search_user.result(distinct: true).page(params[:page]).per(Constants::SEARCH_USER_NUM) if params[:q].present?
        @search_micropost = Micropost.ransack(params[:p], search_key: :p)
        @microposts = @search_micropost.result(distinct: true).includes([:user]).recent.page(params[:page]).per(Constants::SEARCH_MICROPOST_NUM) if params[:p].present?

        render 'static_pages/home'
      else
        # micropost 作成
        @last_task = last_task
        # task 作成, 一覧
        @task = current_user.tasks.build
        @tasks = current_user.tasks.recent
        # task グラフ
        @tasks_today = tasks_day_set(Time.zone.now)
        # Today's task
        @microposts_with_task_today = microposts_with_task(Time.zone.now)

        @show_modal = true
        render 'static_pages/timer'
      end
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "投稿を削除しました！"
    if request.referer.include?('microposts')
      redirect_to root_url
    else
      redirect_back(fallback_location: root_url)
    end
  end

  def show
    @micropost = Micropost.find(params[:id])
    @comment = current_user.comments.build
    @comments = @micropost.comments.includes([:user]).recent.page(params[:page]).per(Constants::COMMENT_NUM)
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content, :task, :task_time)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_comment.html.erb
<li id="comment-<%= comment.id %>">
  <%= link_to gravatar_for(comment.user, size: 50), comment.user %>
  <span class="user"><%= link_to comment.user.name, comment.user %></span>
  <span class="content"><%= safe_join(comment.content.split("\n"), tag(:br)) %></span>
  <span class="timestamp">
    <%= time_ago_in_words(comment.created_at) %>前
    <% if current_user == comment.user %>
      <%= link_to "削除", micropost_comment_path(comment.micropost.id, comment.id), method: :delete, data: { confirm: "本当に削除しますか？" } %>
    <% end %>
  </span>
</li>

app/views/microposts/_comment_form.html.erb
<%= form_with(model: [micropost, comment], local: true, id: "comment-form-with") do |f| %>
  <%= render 'shared/error_messages', errors_num_unnecessary: true, object: f.object %>
  <div class="field">
    <%= f.hidden_field :micropost_id, value: micropost.id %>
    <%= f.text_area :content, placeholder: "Content", id: "comment-content-area", maxlength: 200 %>
  </div>
  <%= button_tag type: "submit", class: "btn btn-success btn-block", id: "btn-post" do %>
    <i class="far fa-comments"></i> コメント
  <% end %>
<% end %>

app/views/microposts/_micropost_show.html.erb
<div id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <% if micropost.task %>
    <div class="task-info">
      <span class="task">#<%= micropost.task %></span>
      <span class="task-time"> (<%= micropost.task_time %>)</span>
    </div><br>
  <% end %>
  <span class="content"><%= safe_join(micropost.content.split("\n"), tag(:br)) %></span>
  <span class="timestamp">
    <div class="time-ago"><%= time_ago_in_words(micropost.created_at) %>前</div>
    <%= render 'shared/like', micropost: micropost %>
    <% if current_user == micropost.user %>
      <%= link_to "削除", micropost, method: :delete, data: { confirm: "本当に削除しますか？" } %>
    <% end %>
  </span>
</div>

app/views/microposts/show.html.erb
<% provide(:title, "コメント") %>
<div class="row">
  <aside class="col-md-4">
    <%= render 'shared/aside_profile', users: nil, user: current_user %>
    <section class="comment_form">
      <%= render 'microposts/comment_form', micropost: @micropost, comment: @comment %>
    </section>
  </aside>
  <div class="col-md-8">
    <div class="microposts">
      <%= render 'microposts/micropost_show', micropost: @micropost %>
    </div>
    <% if @comments.any? %>
      <h3 class="comment-title">Comments (<%= @micropost.comments.count %>)</h3>
      <div class="comments-wrapper">
        <ol class="comments">
          <% @comments.each do |comment| %>
            <%= render 'microposts/comment', comment: comment %>
          <% end %>
        </ol>
      </div>
      <%= paginate @comments %>
    <% end %>
  </div>
</div>