config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/policy', to: 'static_pages#policy'
  get '/timer', to: 'static_pages#timer'
  get '/week', to: 'static_pages#week'
  post '/week', to: 'static_pages#week_specified'
  get '/month', to: 'static_pages#month'
  post '/month', to: 'static_pages#month_specified'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: "users/confirmations",
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: :show do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy, :show] do
    resources :comments, only: [:create, :destroy]
  end
  resources :tasks, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/views/layouts/_flash.html.erb
<%# deviseのflash keyが [:notice] および [:alert] のためレイアウトを統一 %>
<% flash.each do |message_type, message| %>
  <% if message_type.to_s == "notice" %>
    <div class="alert alert-success"><%= message %></div>
  <% elsif message_type.to_s == "alert" %>
    <div class="alert alert-danger"><%= message %></div>
  <% else %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li class="policy-link"><%= link_to "利用規約", policy_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <nav class="navbar navbar-expand-md navbar-light bg-original fixed-top">
      <%= link_to root_path, id: "logo" do %>
        <img src="https://fontmeme.com/permalink/200922/f847879e5067d5ad9b79f09d276a9bc4.png" alt="font-instagram" border="0">
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#responsiveMenu" aria-controls="responsiveMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="responsiveMenu">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to root_path, class: "nav-link" do %>
              <i class="fas fa-home fa-lg"></i> ホーム
            <% end %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to timer_path, data: {"turbolinks" => false}, class: "nav-link" do %>
                <i class="fas fa-stopwatch fa-lg"></i> タスク
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to user_path(current_user), class: "nav-link" do %>
                <i class="far fa-user fa-lg"></i> プロフィール
              <% end %>
            </li>
            <li class="nav-item">
              <%= render 'shared/notifications' %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
                <i class="fas fa-door-open fa-lg"></i> ログアウト
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: "nav-link" do %>
                <i class="fas fa-user-plus fa-lg"></i> ユーザー登録
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: "nav-link" do %>
                <i class="fas fa-door-closed fa-lg"></i> ログイン
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/_js.html.erb
<!-- Sweet Alert2 -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(page_title: yield(:title)) %></title>
    <%= render 'layouts/head' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/flash' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/js' %>
  </body>
</html>